services:
  web:
    image: ndi_record:master
    runtime: nvidia
    network_mode: host
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - /run/avahi-daemon/socket:/run/avahi-daemon/socket
      - /var/run/dbus:/var/run/dbus
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /home/bvsc-oxit/RECORDINGS:/app/output/
