services:
  web:
    image: ndi_record
    runtime: nvidia
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    network_mode: host
    privileged: true
    # ports:
    #   - 8000:8000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ./app:/app/app
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /run/avahi-daemon/socket:/run/avahi-daemon/socket
      - /var/run/dbus:/var/run/dbus
