schedule:
  start_time: null
  end_time: null
  duration: "00:01"

out_path: ./output

camera_system:

  cameras:
    ptz1:
      name: Avonic_CM93_NDI
      enable: True
      ip: 192.168.16.11
      visca_port: 52381
      src: ndi
      fps: 30
      presets:
        left: [65286, 65158]
        center: [0x1000c, 0xfe64]
        right: [65777, 65158]
      camera_params: null
      speed: 0x10
      stream: True
    ptz2:
      name: Avonic_CM93_NDI
      enable: True
      ip: 192.168.16.12
      visca_port: 52381
      src: ndi
      fps: 30
      presets:
        left: [65051, 65149]
        center: [0x1002a, 0xfe4d]
        right: [66018, 65143]
      camera_params: null
      speed: 0x10
    pano:
      name: Vivotek-MS9321-EHV-V2
      enable: True
      ip: 192.168.16.13
      # src: rtsp
      src: rtsp://192.168.16.13:554/media2/stream.sdp?profile=Profile200
      frame_size: [4096, 1484]
      crop: [530, 850, 1120, 3660] # (top_y, top_x, bottom_y, bottom_x)
      fps: 20
      camera_params: ./camera_params/bvsc/pano_params_bvsc.npy
      save: True

  pano_onnx: ./models/rtdetrv2_pano.onnx
  track_threshold: 2.0
  
bev:
  points:
    world: [[-25, 10], [25, 10], [-25, -10], [25, -10]]
    image: [[549, 103], [2315, 71], [73, 470], [2746, 407]]
  court_size: [25, 20]