schedule:
  start_time: null
  end_time: null
  duration: "00:30"

out_path: ./output

camera_system:
  cameras:
    ptz1:
      name: Avonic-CM93-NDI
      enable: True
      ip: 192.168.33.101
      src: ndi
      fps: 30
      presets:
        left: [0xff06, 0xfe86]
        center: [0x1000c, 0xfe64]
        right: [0x100f1, 0xfe86]
      speed: 0x10
    ptz2:
      name: Avonic-CM93-NDI
      enable: True
      ip: 192.168.33.102
      src: ndi
      fps: 30
      presets:
        left: [0xfe1b, 0xfe7d]
        center: [0x1002a, 0xfe4d]
        right: [0x101e2, 0xfe77]
      speed: 0x10
    pano:
      name: Vivotek-MS9321-EHV-V2
      enable: True
      ip: 169.254.108.83
      # src: rtsp
      #src: rtsp://192.168.33.103:554/media2/stream.sdp?profile=Profile200
      src: /home/bvsc-oxit/Documents/BACKUP/Only_For_Testing/ndi_recording/dataset/input/cropped_3.mp4
      frame_size: [4416, 1600]
      crop: [530, 850, 1120, 3660] # (top_y, top_x, bottom_y, bottom_x)
      fps: 15
  
pano_onnx: onnx/rtdetrv2.onnx