schedule:
  start_time: null
  end_time: null
  duration: "00:01"

out_path: ./output

camera_system:
  cameras:
    ptz1:
      name: Avonic-CM93-NDI
      enable: True
      ip: 169.254.108.81
      src: ndi
      fps: 30
      presets:
        left: [0xfd63, 0x0]
        center: [0x0, 0x0]
        right: [0x38c, 0x0]
      speed: 0x10
    ptz2:
      name: Avonic-CM93-NDI
      enable: True
      ip: 169.254.108.82
      src: ndi
      fps: 30
      presets:
        left: [0x38c, 0x0]
        center: [0x0, 0x0]
        right: [0x351, 0x0]
      speed: 0x10
    pano:
      name: Vivotek-MS9321-EHV-V2
      enable: True
      ip: 169.254.108.83
      # src: rtsp
      src: rtsp://169.254.108.83:554/media2/stream.sdp?profile=Profile200
      # src: /home/geri/Desktop/pano_cut.mp4
      frame_size: [4416, 1600]
      crop: [420, 1150, 1190, 3390] # (top_y, top_x, bottom_y, bottom_x)
      fps: 15
  
pano_onnx: onnx/rtdetrv2.onnx